
###
GET http://localhost:8080/api/getUsers?accountStatus=Disabled
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYXZhbGNyb213ZWxsQGdtYWlsLmNvbSIsInJvbGUiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTc3NjQzNDg1MywiZXhwIjoxNzc2NTIxMjUzfQ.0I-6dyVcvqv9jbOiQqKh_Z7FrcrMYFNLAQwm4KrsT1MQReaZANxaGISgkKT36kpm


###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "dexter.dgmc@gmail.com",
  "name": "Dexter",
  "password": "Radiologist@123",
  "role": {
    "roleId": 3
  }
}

###
PUT http://localhost:8080/api/disableUser/3
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYXZhbGNyb213ZWxsQGdtYWlsLmNvbSIsInJvbGUiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTc3NjQzNDg1MywiZXhwIjoxNzc2NTIxMjUzfQ.0I-6dyVcvqv9jbOiQqKh_Z7FrcrMYFNLAQwm4KrsT1MQReaZANxaGISgkKT36kpm

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "navalcromwell@gmail.com",
  "password": "Admin@123"
}

###
GET http://localhost:8080/api/getRoles?deparmentName=ICT
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYXZhbGNyb213ZWxsQGdtYWlsLmNvbSIsInJvbGUiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTc3NjMyNTIyOSwiZXhwIjoxNzc2NDExNjI5fQ.08ftM6WzXGfHpVRHQRfxSQd0nA7ier2FoY1nHsHt_p5AItyDU0Pot-qqXdGGvvq7

###
POST http://localhost:8080/api/createRole
Content-Type: application/json

{
  "roleName": "Radio FrontDesk",
  "department": {
    "departmentId": 2
  }
}

###
PUT http://localhost:8080/api/archiveRole/6
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYXZhbGNyb213ZWxsQGdtYWlsLmNvbSIsInJvbGUiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTc3NjQwMjY2MywiZXhwIjoxNzc2NDg5MDYzfQ.Nd5fRE2-5Hdd0gfEMtBQ55Q6Nw0UrjFy6EeXf0FVGP-uJPgLlETjrf1hVf1t6z-t


###
POST http://localhost:8080/api/createDepartment
Content-Type: application/json

{
  "departmentName": "Rehabilitation"
}

###
GET http://localhost:8080/api/getDepartments?departmentStatus=Active
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYXZhbGNyb213ZWxsQGdtYWlsLmNvbSIsInJvbGUiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTc3NjQ5OTAyMywiZXhwIjoxNzc2NTg1NDIzfQ.RuDLumnXUlDeoHSfNntl0fumgGNzV5BOJZdcB5eyDOaLUyVVF9pQp7LCkedck1am


###
GET http://localhost:8080/api/searchDepartment/Radio
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYXZhbGNyb213ZWxsQGdtYWlsLmNvbSIsInJvbGUiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTc3NjMyNTIyOSwiZXhwIjoxNzc2NDExNjI5fQ.08ftM6WzXGfHpVRHQRfxSQd0nA7ier2FoY1nHsHt_p5AItyDU0Pot-qqXdGGvvq7


###
PUT http://localhost:8080/api/updateDepartment/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYXZhbGNyb213ZWxsQGdtYWlsLmNvbSIsInJvbGUiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTc3NjMyNTIyOSwiZXhwIjoxNzc2NDExNjI5fQ.08ftM6WzXGfHpVRHQRfxSQd0nA7ier2FoY1nHsHt_p5AItyDU0Pot-qqXdGGvvq7
Content-Type: application/json

{
  "departmentId": 2,
  "departmentName": "Radiology"
}

###
PUT http://localhost:8080/api/archiveDepartment/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYXZhbGNyb213ZWxsQGdtYWlsLmNvbSIsInJvbGUiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTc3NjQ5OTAyMywiZXhwIjoxNzc2NTg1NDIzfQ.RuDLumnXUlDeoHSfNntl0fumgGNzV5BOJZdcB5eyDOaLUyVVF9pQp7LCkedck1am


###
PUT http://localhost:8080/api/restoreDepartment/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYXZhbGNyb213ZWxsQGdtYWlsLmNvbSIsInJvbGUiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTc3NjMyNTIyOSwiZXhwIjoxNzc2NDExNjI5fQ.08ftM6WzXGfHpVRHQRfxSQd0nA7ier2FoY1nHsHt_p5AItyDU0Pot-qqXdGGvvq7


###
POST http://localhost:8080/api/createMachine
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYXZhbGNyb213ZWxsQGdtYWlsLmNvbSIsInJvbGUiOlt7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTc3NjMyNTIyOSwiZXhwIjoxNzc2NDExNjI5fQ.08ftM6WzXGfHpVRHQRfxSQd0nA7ier2FoY1nHsHt_p5AItyDU0Pot-qqXdGGvvq7
Content-Type: application/json

{
  "machineName": "Ultrasound"
}