###
POST http://localhost:8080/Roles/CreateRole
Content-Type: application/json

{
  "roleName": "Admin",
  "department": {
    "departmentId": 1
  }
}

###
POST http://localhost:8080/Departments/createDepartment
Content-Type: application/json

{
  "departmentName": "ICT"
}

###
GET http://localhost:8080/Departments/getDepartments

###
PUT http://localhost:8080/Departments/updateDepartment/3
Content-Type: application/json

{
  "departmentName": "ICT"
}


###
POST http://localhost:8080/Users/createUser
Content-Type: application/json

{
  "role": {
    "roleId": 6
  },
  "accountStatus": "Active",
  "name": "Cromwell Naval",
  "email": "navalcromwell@gmail.com",
  "password": "ICTD@123"
}

###
GET localhost:8080/Users/getUsers


